name: GO # 工作流名称

on: 
    schedule:
        - cron: '0 0 * * *'  # 每天UTC午夜
    workflow_dispatch:  # 手动触发工作流
jobs:  # 定义作业
  build-job:  # 作业ID
    runs-on: ubuntu-latest  # 运行环境
    steps:
    - name: Set LANG env for zh-CN
      run: |
        echo "LANG=zh_CN.UTF-8" >> $GITHUB_ENV
        echo "LANGUAGE=zh_CN:zh" >> $GITHUB_ENV

    - uses: browser-actions/setup-edge@v1
    # - name: Print Edge version
    #   run: (Get-Item (Get-Command msedge).Source).VersionInfo.ProductVersion

    - name: edgedriver
      run: |
            wget https://msedgedriver.microsoft.com/136.0.3240.64/edgedriver_linux64.zip

            unzip edgedriver_linux64.zip
            chmod +x msedgedriver
            sudo mv msedgedriver /usr/local/bin/


            # 检查配置文件路径
            CONFIG_FILE="$HOME/.config/microsoft-edge/Default/preferences"

            # 修改配置文件，将语言设置为简体中文
            if [ -f "$CONFIG_FILE" ]; then
                echo "Modifying language settings..."
                # 使用 sed 修改语言设置
                sed -i 's/"intl.accept_languages": "en-US,en;q=0.9"/"intl.accept_languages": "zh-CN,zh;q=0.9"/g' "$CONFIG_FILE"
                echo "Language set to Chinese (zh-CN)."
            else
                echo "Edge configuration file not found. Please ensure Edge is installed."
            fi
            

            export LANGUAGE=ZH-CN.UTF-8
            echo “export LANGUAGE=ZH-CN.UTF-8” >> /usr/bin/microsoft-edge


            




    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Run python script find1.py  
      run: |
            pip install selenium numpy wget requests
            ls -l
            python find1.py
            cat src.txt

    - name: Run python script find2download.py
      run: |
            python find2download.py
            cat download.txt
            cat webimg.txt
            ls -l
    
    - name: unzip and remove zip file
      run: |
            python unzip.py
            ls -l


    - name: Run python script calendar.py
      run: |
        pip install selenium numpy wget requests
        ls -l
        cd ./日历壁纸
        python calendardownloader.py
        ls -l
    
    - name: generate html
      run: |
        python show.py
        ls -l



    - name: Commit files
      run: |
        git add .
        git status
        ls  -l
        git config --local user.email "luqizhi666@gmail.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "AUTO"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

