name: GO # 工作流名称

on: 
    schedule:
        - cron: '0 0 * * *'  # 每天UTC午夜
    workflow_dispatch:  # 手动触发工作流
jobs:  # 定义作业
  build-job:  # 作业ID
    runs-on: ubuntu-latest  # 运行环境
    steps:
    - uses: browser-actions/setup-edge@v1
    # - name: Print Edge version
    #   run: (Get-Item (Get-Command msedge).Source).VersionInfo.ProductVersion

    - name: edgedriver
      run: |
            wget https://msedgedriver.microsoft.com/136.0.3240.64/edgedriver_linux64.zip

            unzip edgedriver_linux64.zip
            chmod +x msedgedriver
            sudo mv msedgedriver /usr/local/bin/




    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Run python script find1.py  
      run: |
            pip install selenium numpy wget requests
            ls -l
            python find1.py
            cat src.txt

    - name: Run python script find2download.py
      run: |
            python find2download.py
            cat download.txt
            cat webimg.txt
            ls -l
    
    - name: unzip and remove zip file
      run: |
            python unzip.py
            ls -l


    - name: Run python script calendar.py
      run: |
        cd .\日历壁纸\calender.py
        python calendar.py
        ls -l
