name: GO # 工作流名称

on: 
    schedule:
        - cron: '0 0 * * *'  # 每天UTC午夜
    workflow_dispatch:  # 手动触发工作流
jobs:  # 定义作业
  build-job:  # 作业ID
    runs-on: ubuntu-latest  # 运行环境
    steps:
    - uses: browser-actions/setup-edge@v1
    # - name: Print Edge version
    #   run: (Get-Item (Get-Command msedge).Source).VersionInfo.ProductVersion

    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Run python script find1.py and find2download.py
      run: |
            ls -l
            python find1.py
            cat src.txt
            python find2download.py
            cat download.txt
            cat webimg.txt
            ls -l
    - name: Run python script calendar.py
      run: |
        cd .\日历壁纸\calender.py
        python calendar.py
        ls -l
